### ISSUE TITLE
Error appear when I am creating Folder 

### ISSUE THREAD

**Issue by shajahan86** [Alfresco/alfresco-java-sdk#128]
Hi,
When I am trying to create folder. it is shows following error.
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:805) ~[spring-boot-2.5.8.jar:2.5.8]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:786) ~[spring-boot-2.5.8.jar:2.5.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345) ~[spring-boot-2.5.8.jar:2.5.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-2.5.8.jar:2.5.8]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.8.jar:2.5.8]
	at com.alfresco.alfresco.AlfrescoApplication.main(AlfrescoApplication.java:26) ~[classes/:na]
Caused by: feign.FeignException$BadRequest: [400 Bad Request] during [POST] to [http://localhost:8080/alfresco/api/-default-/public/alfresco/versions/1/nodes/-root-/children?autoRename=true&majorVersion=true&versioningEnabled=true] [NodesApiClient#createNode(String,NodeBodyCreate,Boolean,Boolean,Boolean,List,List)]: [{"error":{"errorKey":"Could not read content from HTTP request body: Unrecognized field \"definition\" (Class org.alfresco.rest.api.model.Node), not marked as ignorable\n at [Source: java.io.BufferedR... (827 bytes)]
	at feign.FeignException.clientErrorStatus(FeignException.java:195) ~[feign-core-10.12.jar:na]
	at feign.FeignException.errorStatus(FeignException.java:177) ~[feign-core-10.12.jar:na]
	at feign.FeignException.errorStatus(FeignException.java:169) ~[feign-core-10.12.jar:na]
	at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:92) ~[feign-core-10.12.jar:na]
	at feign.AsyncResponseHandler.handleResponse(AsyncResponseHandler.java:96) ~[feign-core-10.12.jar:na]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138) ~[feign-core-10.12.jar:na]
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89) ~[feign-core-10.12.jar:na]
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100) ~[feign-core-10.12.jar:na]
	at jdk.proxy2/jdk.proxy2.$Proxy87.createNode(Unknown Source) ~[na:na]
	at com.alfresco.alfresco.AlfrescoApplication.createFolder(AlfrescoApplication.java:68) ~[classes/:na]
	at com.alfresco.alfresco.AlfrescoApplication.run(AlfrescoApplication.java:34) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:802) ~[spring-boot-2.5.8.jar:2.5.8]

**Comment by jlosornogil** [comment]
Hi @shajahan86, could you please share the version number of the Alfresco Java SDK that you've used in your project and the code that invokes the creation of the folder? Thanks!
